# A function defines the task we're tackling (e.g. generating a haiku)...
[functions.generate_haiku]
type = "chat"

# ... and a variant is one of many implementations we can use to tackle it (a choice of prompt, model, etc.).
# Since we only have one variant for this function, the gateway will always select it.
[functions.generate_haiku.variants.rust_proxy]
type = "chat_completion"
model = "rust-proxy"

# Configure the rust-proxy model
[models.rust-proxy]
routing = ["rust_proxy_provider"]

[models.rust-proxy.providers.rust_proxy_provider]
type = "rust-proxy" 