# A function defines the task we're tackling (e.g. generating a haiku)...
[functions.generate_haiku]
type = "chat"

# ... and a variant is one of many implementations we can use to tackle it (a choice of prompt, model, etc.).
# Since we only have one variant for this function, the gateway will always select it.
[functions.generate_haiku.variants.rust_proxy]
type = "chat_completion"
model = "rust-proxy"

# Configure the rust-proxy model with comprehensive options
[models.rust-proxy]
routing = ["rust_proxy_provider"]

[models.rust-proxy.providers.rust_proxy_provider]
type = "rust-proxy"
model_name = "claude-3.5-sonnet"

# API Configuration (optional - defaults will be used if not specified)
api_endpoint = "https://api.devv.ai/api/v1/stream/chat"
device_id = "your-device-id-here"
session_id = "your-session-id-here"
os_type = "3"
accept_language = "en"

# Model filtering options (optional)
[models.rust-proxy.providers.rust_proxy_provider.model_filter]
include_types = ["base", "freeTrial"]  # Only include free models
# exclude_types = ["premium"]         # Uncomment to exclude premium models
min_usage_left = 5                    # Minimum usage count required
only_new = false                      # Set to true to only show new models 